{{- if .Values.slack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finops-enforcer.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "finops-enforcer.labels" . | nindent 4 }}
type: Opaque
stringData:
  slack-webhook-url: {{ .Values.slack.webhookURL | quote }}
{{- end }}
